{{- $syslogNg := .Values.configOverrides.syslog_ng | replace "format" .Values.storage.connections.format -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "log-collector.fullname" . }}-config
data:
  syslog-ng.conf: {{ $syslogNg | quote }}
  base_tbl.sql: {{ .Values.configOverrides.base_query | quote }}

