apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "log-collector.fullname" . }}-storage
  labels:
    {{- include "log-collector.labels" . | nindent 4 }}
    app: {{ include "log-collector.fullname" . }}-storage
spec:
  {{- if not .Values.storage.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "log-collector.selectorLabels" . | nindent 6 }}
      app: {{ include "log-collector.fullname" . }}-storage
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "log-collector.labels" . | nindent 8 }}
        app: {{ include "log-collector.fullname" . }}-storage
	{{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "log-collector.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.storage.securityContext | nindent 12 }}
          image: "{{ .Values.storage.repository }}:{{ .Values.storage.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.storage.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.storage.connections.http_port | int }}
              protocol: TCP
            - name: native
              containerPort: {{ .Values.storage.connections.native_port | int }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
            timeoutSeconds: 5
          {{- with .Values.storage.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config-volume
              mountPath: /configmap
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "sleep 2; clickhouse-client --queries-file /configmap/base_tbl.sql"]
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "log-collector.fullname" . }}-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
