apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "log-collector.fullname" . }}-ch
  labels:
    {{- include "log-collector.labels" . | nindent 4 }}
spec:
  {{- if not .Values.clickhouse.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "log-collector.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "log-collector.labels" . | nindent 8 }}
	{{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "log-collector.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.clickhouse.securityContext | nindent 12 }}
          image: "{{ .Values.clickhouse.repository }}:{{ .Values.clickhouse.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.clickhouse.pullPolicy }}
          ports:
            - name: http
              containerPort: 8123
              protocol: TCP
            - name: native
              containerPort: 9000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
            timeoutSeconds: 5
          resources:
            requests:
              memory: "1024Mi"
              cpu: "1000m"
            limits:
              memory: "14000Mi"
              cpu: "3500m"
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "sleep 2; clickhouse-client --database default --query 'CREATE TABLE basic_logger (created_at String, host String, message String) ENGINE = MergeTree() ORDER BY created_at;'"]
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
