apiVersion: v1
kind: Service
metadata:
  name: {{ include "log-collector.fullname" . }}-ch
  labels:
    {{- include "log-collector.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8123
      targetPort: http
      protocol: TCP
      name: http
    - port: 9000
      targetPort: native
      protocol: TCP
      name: native
  selector:
    {{- include "log-collector.selectorLabels" . | nindent 4 }}
