apiVersion: v1
kind: Service
metadata:
  name: {{ include "log-collector.fullname" . }}-collector
  labels:
    {{- include "log-collector.labels" . | nindent 4 }}
    app: {{ include "log-collector.fullname" . }}-collector
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.collector.connections.tcp_port | int }}
      targetPort: {{ .Values.collector.connections.tcp_port | int }}
      protocol: TCP
      name: tcpt
    - port: {{ .Values.collector.connections.udp_port | int }}
      targetPort: {{ .Values.collector.connections.udp_port | int }}
      protocol: UDP
      name: udpt
  selector:
    {{- include "log-collector.selectorLabels" . | nindent 4 }}
    app: {{ include "log-collector.fullname" . }}-collector

