apiVersion: v1
kind: Service
metadata:
  name: {{ include "log-collector.fullname" . }}-gui
  labels:
    {{- include "log-collector.labels" . | nindent 4 }}
    app: {{ include "log-collector.fullname" . }}-gui
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.gui.connections.port | int }}
      targetPort: 8000
      protocol: TCP
      name: gui-http
  selector:
    {{- include "log-collector.selectorLabels" . | nindent 4 }}
    app: {{ include "log-collector.fullname" . }}-gui
